config/routes.rb
Rails.application.routes.draw do
  get '/auth/:provider/callback', to: 'sessions#add'
  get '/auth/failure', to: redirect('/')

  get 'signout/:provider', to: 'sessions#destroy', as: 'signout'
  resources :posts, only: [:new, :create]
  root to: 'posts#new'

  get '/dialog/oauth', to: 'sessions#add'
end

app/models/identity.rb
#
class Identity < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |identity|
      identity.provider = auth.provider
      identity.uid = auth.uid
      identity.oauth_token = auth.credentials.token
      identity.oauth_secret = auth.credentials.secret
      identity.refresh_token = auth.credentials.refresh_token
      identity.instance_url = auth.credentials.instance_url
      instance_eval("identity.get_profile_data_from_#{identity.provider}(auth)")
      identity.save!
    end
  end

  def get_profile_data_from_facebook(auth)
    self.screen_name = auth.info.name
    self.url = auth.info.urls.Facebook
    self.image_url = auth.info.image
  end

  def get_profile_data_from_twitter(auth)
    self.screen_name = auth.info.nickname
    self.url = auth.info.urls.Twitter
    self.image_url = auth.info.image
  end

  def get_profile_data_from_salesforce(auth)
    self.screen_name = auth.info.name
    self.url = auth.info.urls.profile
    self.image_url = auth.info.image
  end

  def get_profile_data_from_linkedin(auth)
    self.screen_name = auth.info.name
    self.url = auth.info.urls.public_profile
    self.image_url = auth.info.image
  end
end

app/models/poster.rb
#
class Poster
  include ApplicationHelper
  attr_accessor :body, :providers, :author, :status, :logins
  POST_METHODS = { twitter: 'update(post)',
                   facebook: 'put_connections("me", "feed", :message => post)',
                   linkedin: 'add_share(:comment => post)',
                   salesforce: 'post_status(post)' }

  def initialize(post, logins)
    @body = post[:body]
    @providers = get_providers(post)
    @status = {}
    @logins = logins
  end

  def batch_publish
    providers.each do |provider|
      if logins[provider]
        @author = Identity.where(provider: provider,
                                 uid: logins[provider]).first
        status[provider] = instance_eval("post_to_#{provider}(body)")
      else
        status[provider] = "You cannot post on #{pretty_provider_name(provider)}
                        until you log in. To log in, just click the link above."
      end
    end
  end

  private

  POST_METHODS.keys.each do |provider|
    class_eval %(
      def post_to_#{provider}(post)
        client = set_up_#{provider}_client
        begin
          outcome = 'Success!' if client.#{POST_METHODS[provider]}
        rescue
          outcome = "Error. Try again or try posting directly on
                     #{provider.to_s.humanize} website."
        end
        outcome
      end
    )
  end

  def get_providers(args)
    result = []
    POST_METHODS.keys.each do |provider|
      result << provider if args[provider.to_s] == '1'
    end
    result
  end

  def set_up_twitter_client
    client = Twitter::REST::Client.new do |config|
      config.consumer_key = ENV['TWITTER_KEY']
      config.consumer_secret = ENV['TWITTER_SECRET']
      config.access_token = author.oauth_token
      config.access_token_secret = author.oauth_secret
    end
    client
  end

  def set_up_salesforce_client
    client = Databasedotcom::Client.new client_id: ENV['SALESFORCE_KEY'],
                                        client_secret: ENV['SALESFORCE_SECRET']
    client.authenticate token: author.oauth_token,
                        instance_url: author.instance_url,
                        refresh_token: author.refresh_token
    client.version = '23.0'
    Databasedotcom::Chatter::User.find(client, 'me')
  end

  def set_up_facebook_client
    Koala::Facebook::API.new(author.oauth_token)
  end

  def set_up_linkedin_client
    client = LinkedIn::Client.new(ENV['LINKEDIN_KEY'], ENV['LINKEDIN_SECRET'])
    client.authorize_from_access(author.oauth_token, author.oauth_secret)
    client
  end
end

app/controllers/application_controller.rb
#
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_identity, :logged_in?

  def logged_in?(provider)
    !session[provider].nil?
  end

  def current_identity(provider)
    return unless logged_in?(provider)
    Identity.where(provider: provider, uid: session[provider]).first
  end
end

app/controllers/posts_controller.rb
#
class PostsController < ApplicationController
  def new
  end

  def create
    @poster = Poster.new(params[:post], logins_from_session)
    @poster.batch_publish
    render '/posts/create', locals: { status: @poster.status }
  end

  private

  def logins_from_session
    result = {}
    Poster::POST_METHODS.keys.each do |provider|
      result[provider] = session[provider] if session[provider]
    end
    result
  end
end

app/controllers/sessions_controller.rb
#
class SessionsController < ApplicationController
  def add
    @identity = Identity.from_omniauth(env['omniauth.auth'])
    session[params['provider']] = @identity.uid
    redirect_to root_path
  end

  def destroy
    session[params['provider']] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def pretty_provider_name(provider)
    provider == :linkedin ? 'LinkedIn' : provider.to_s.humanize
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Batch posting to social networks</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class='container'

      <%= render 'shared/signin_status' %>
      <%= yield %>
      
    </div>
  </body>
</html>

app/views/posts/create.html.haml
.row
  .col-sm-6.col-sm-offset-4.voffset-5
    %h3 Here is just to make sure you post got published:
    - if status.blank?
      %p Well, you decided not to post on any of the platforms... and it went well.
    - else
      - status.each do |provider|
        %p
          %strong= "To #{pretty_provider_name(provider[0])}:"
          = provider[1]
    %br
    %br
    %br
    = link_to 'Post something else', root_path, class: 'btn btn-primary btn-lg'

app/views/posts/new.html.haml
.row
  .col-sm-6.col-sm-offset-4.voffset-5
    %h3 Post an update:
    .form-inline
      = form_for :post, url: posts_path, method: :post do |f|
        = f.text_area :body, cols: 50, rows: 10
        %br
        - Poster::POST_METHODS.keys.each do |provider|
          = f.label provider, "on #{pretty_provider_name(provider)}"
          = f.check_box provider
        %br
        %br
        = f.submit 'Post', class: 'btn btn-success btn-lg'

app/views/shared/_signin_status.html.haml
.row
  - Poster::POST_METHODS.keys.each do |provider|
    .col-sm-3
      - if logged_in?(provider)
        %p
          Logged into 
          %strong= pretty_provider_name(provider)
          as:
          %br
          = link_to current_identity(provider).screen_name, current_identity(provider).url
        %img(src="#{current_identity(provider).image_url}")
        %br
        = link_to 'Sign out', signout_path(provider), id: "signout_#{provider}"
      - else
        = link_to "Sign in to post on #{pretty_provider_name(provider)}", "/auth/#{provider}"